name: flutter_webapi_first_course
description: Projeto do primeiro curso de WebAPI da Formação Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0" #sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  uuid: ^4.4.0 #^3.0.6

  google_fonts: ^6.2.1 #importando google fonts

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 #^2.0.0

flutter:

  uses-material-design: true
